# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MO1PZQM0INWpDjCyQdsoyU7IQICU9X5t
"""

print ("merhaba")

print("Biz fizikçiyiz")



